### ISSUE TITLE
iterator access denied？why？

### ISSUE THREAD

**Issue by NeuralMayu** [js-sdsl/js-sdsl#145]

**Comment by ZLY201** [comment]
Could you give me more information?

Or you just want to know why we checked iterator whether valid?

**Comment by NeuralMayu** [comment]
import { LinkList } from 'js-sdsl';
const LinkListRef = React.useRef(new LinkList());
const computed = React.useRef<any>(null);
LinkListRef.current.pushBack(key);
computed.current = LinkListRef.current.begin();
console.log(LinkListRef.current.size()); // 1
console.log(LinkListRef.current.begin()); 
console.log(LinkListRef.current.end());
console.log(LinkListRef.current.begin().equals(LinkListRef.current.end())); // false
and
![image](https://user-images.githubusercontent.com/82007499/205922529-e9182352-f73a-4870-8600-9e420462df37.png)

**Comment by ZLY201** [comment]
The `end` iterator is a super end for all container.

For example:

index 0 1 2 3 4 5
value 1 2 3 4 5 Error

The `begin` will pointer to index 0 and the value is 1.

The `end` wlill pointer to index 5 and will get a error when run `iteraotr.pointer`.

Same as `rEnd`.

Design ideas from C++ STL.
