### ISSUE TITLE
Find a new way to do publish

### ISSUE THREAD

**Issue by ZLY201** [js-sdsl/js-sdsl#160]
https://github.com/js-sdsl/js-sdsl/actions/runs/3964428948

Since I was forced to enable secondary authentication by npm, the automated CI could not be released successfully.

**Comment by ZLY201** [comment]
Good news!

https://hackernoon.com/publish-npm-packages-using-github-actions-a-how-to-guide-q31c34fg

I will use the new automatic token to do publish next time.

**Comment by noname0310** [comment]
I just tried it and using `Require two-factor authentication or an automation or granular access token` option, publish works well without any code modification.

**Comment by noname0310** [comment]
![image](https://user-images.githubusercontent.com/48761044/226230943-df8cba0e-c455-4e9c-9642-821cd146660c.png)
I think you can close this issue in the next publish.

**Comment by ZLY201** [comment]
Version 4.4.0 successful automatic published.
