### ISSUE TITLE
Question: OrderedSet and comparison function 

### ISSUE THREAD

**Issue by vanodevium** [js-sdsl/js-sdsl#161]
Is there any possibility to use comparison by two fields for a set of objects?

Example: 
I have simple objects, like
```
{
    "id": 1,
    "price": 10
},
{
    "id": 2,
    "price": 9
},
{
    "id": 3,
    "price": 3
}
```

I wanna set of this objects, but ordered by **price ASC** and **id DESC**.
Is it real? 

Thanks for any advice!

**Comment by ZLY201** [comment]
Yes, you can pass a `cmp` param to the `constructor` of the set to do compare.
For example:

```typescript
// create a set which sort by `cmp` function.
const st = new OrderedSet([{ id: 1, price: 10 }], (x, y) => {
  if (x.price === y.price) {
    return y.id - x.id;
  }
  return x.price - y.price;
});
```

**Comment by vanodevium** [comment]
Awesome! Many thanks!

---

Another question:

```
const os = new OrderedSet([{ id: 1, price: 10, date: 12345 }, { id: 2, price: 10, date: 12345 }], (x, y) => {
  if (x.date === y.date) {
    return y.price - x.price;
  }
  return x.date - y.date;
});
```

For this case, I have only one element in the set, despite the fact that there are different ID.

---

In Java, TreeMap and TreeSet classes have **equals()** for processing such cases.

Is there something like this for processing such cases?

**Comment by ZLY201** [comment]
> const os = new OrderedSet([{ id: 1, price: 10, date: 12345 }, { id: 2, price: 10, date: 12345 }], (x, y) => {
>   if (x.date === y.date) {
>     return y.price - x.price;
>   }
>   return x.date - y.date;
> });

Just do a little change:

```typescript
const os = new OrderedSet([{ id: 1, price: 10, date: 12345 }, { id: 2, price: 10, date: 12345 }], (x, y) => {
  if (x.date === y.date) {
    if (x.price === y.price) {
        return y.id - x.id;
    }
    return y.price - x.price;
  }
  return x.date - y.date;
});
```

And then all the element will be saved to set.

**Comment by vanodevium** [comment]
Thanx!
