### ISSUE TITLE
`isAccessible` property for iterators?

### ISSUE THREAD

**Issue by x11x** [js-sdsl/js-sdsl#177]
**Is your feature request related to a problem? Please describe.**

This is not really a problem, but I noticed accessing an iterator's pointer causes users some confusion (e.g. #145).

From what I can tell, the correct way to check if an iterator's pointer can be accessed varies slightly for each collection, but is usually something like (given collection, `collection`, and the appropriate iterator instance, `it`):
```js
!it.equals(collection.end())
```

**Describe the solution you'd like**

I wonder if it is a good idea to have an `isAccessible` boolean getter on all the iterators so you can check if it can be accessed. 

**Describe alternatives you've considered**
Otherwise you can just try to access it and catch the `RangeError`, but this is not the best practice in JavaScript (errors are best used for genuine runtime errors etc. rather than for logic).

Users making sure they understand how the collection works and when the pointer can be accessed or not is always a good idea, of course :wink:.

**Additional context**

This could also help with enhancing the code readability and self-documenting, as there would be functions defined in the source providing definitive way of checking if the pointer can be accessed.

**Comment by ZLY201** [comment]
Looks good, I will consider adding this field in the next version.

**Comment by ZLY201** [comment]
Version 4.4.2 has been published. @x11x
