### ISSUE TITLE
Tree shaking not work with js-sdsl

### ISSUE THREAD

**Issue by ZLY201** [js-sdsl/js-sdsl#19]
**Describe the bug**

Tree shaking not work with js-sdsl when use `import { xxx } from 'js-sdsl'`

**To Reproduce**

**Expected behavior**

Tree shaking should work.

**Screenshots**

**Additional context**

See [here](https://github.com/The-World-Space/the-world-engine.ts/pull/50).

**Comment by aladdin-add** [comment]
you can also set the target to es6, so the classes won't be compiled. :)

**Comment by ZLY201** [comment]
> you can also set the target to es6, so the classes won't be compiled. :)

I've try this, but tree-shaking still dones't work in some case and`sideEffects: false` works fine.

Guess it has something wrong with some configs of the user.

**Comment by ZLY201** [comment]
Version 4.1.4 published.
