### ISSUE TITLE
Queue is empty, but the last value still exists

### ISSUE THREAD

**Issue by noname0310** [js-sdsl/js-sdsl#20]
**Describe the bug**
The last value comes out even though the size of the queue is 0.

**To Reproduce**
``` typescript
import { Queue } from "js-sdsl";

const testQueue = new Queue<number>();
testQueue.push(1);
testQueue.push(2);

console.log(testQueue.front(), testQueue.size());
testQueue.pop();
console.log(testQueue.front(), testQueue.size());
testQueue.pop();
console.log(testQueue.front(), testQueue.size());
```

**Expected behavior**
expected behavior is:
```
1 2
2 1
undefined 0
```

actual result is:
```
1 2
2 1 
2 0
```

**Additional context**
There was a similar problem with version 4.1.2 and it was fixed in 4.1.3

This problem occurred again in 4.1.4-beta.0

In my opinion, adding operations on empty containers to the test case will prevent recurrence of this problem in future updates.

**Comment by ZLY201** [comment]
Sorry about that, we will fix it in the next version.

**Comment by ZLY201** [comment]
Version 4.1.4 published.
