### ISSUE TITLE
Reduce packaging size

### ISSUE THREAD

**Issue by ZLY201** [js-sdsl/js-sdsl#23]

**Comment by ZLY201** [comment]
Related issues:

- https://github.com/luin/ioredis/issues/1649
- https://github.com/sidorares/node-mysql2/issues/1629

**Comment by ZLY201** [comment]
@noname0310 Are you interested in this question and have time to solve it?

This requires us to support single module loading.

**Comment by noname0310** [comment]
Are we supposed to load only the packages that the user wants to use `require`?

**Comment by ZLY201** [comment]
> Are we supposed to load only the packages that the user wants to use `require`?

Yes, my idea is to implement `const xxx = require("js-sdsl/xxx");`;

**Comment by noname0310** [comment]
I got it. I'll try

**Comment by noname0310** [comment]
I tested it and it seems that it is already possible to reduce the size of the package size.

## Import from "js-sdsl"
![image](https://user-images.githubusercontent.com/48761044/189793786-7a9fc4a0-e961-4f89-9ecd-584371118e9e.png)

## import from "js-sdsl/dist/cjs/container/SequentialContainer/Vector"
![image](https://user-images.githubusercontent.com/48761044/189793822-af336900-f436-4eb3-bee3-9cbb66dec14e.png)

You can use
``` typescript
const Vector = require("js-sdsl/dist/cjs/container/SequentialContainer/Vector").default as typeof import("js-sdsl/dist/cjs/container/SequentialContainer/Vector").default;
```
instead of 
``` typescript
const { Vector } = require("js-sdsl") as typeof import("js-sdsl");
```

And this is what I found out while doing this. Since we do not generate d.ts for cjs `require`, we need to write the `typeof` in this way to write it in the typescript

https://github.com/noname0310/js-sdsl-cjs-test
test code is here

**Comment by ZLY201** [comment]
Because require cannot be typed. `require` uses commonjs and it's default type is any.

`const Vector = require("js-sdsl/dist/cjs/container/SequentialContainer/Vector").default as typeof import("js-sdsl/dist/cjs/container/SequentialContainer/Vector").default;
`

We do not recommend import by this way.

We need to expose multiple high-maintenance entries but not `dist/xxx`.

Not everybody use webpack so tree-shaking may not work.

**Comment by noname0310** [comment]
In order to reduce the build result, the source must be analyzed and unnecessary sources must be excluded through the bundler.
In this case, some degree of tree shaking should be premised.

**Comment by ZLY201** [comment]
Yes, one of the way is to publish independent package.

But this is a bit troublesome because I didn't think about it when I first wrote.

Do we have a better way?

**Comment by ZLY201** [comment]
Some packages like `ioredis` just use `tsc` to do compile.

**Comment by noname0310** [comment]
> Yes, one of the way is to publish independent package.
> 
> But this is a bit troublesome because I didn't think about it when I first wrote.
> 
> Do we have a better way?

I think it's best to publish separately for each container. For users who want to use only certain containers,

**Comment by noname0310** [comment]
I'll create a build solution for this

**Comment by ZLY201** [comment]
https://github.com/js-sdsl/js-sdsl/actions/runs/3163428534/jobs/5150981144

It seems that github actions doesn't support local `ts-node` command.

I will fix it next version and publish isolate packages locally tonight.

**Comment by ZLY201** [comment]
All isolate packages published. I'll do a test for them later.

**Comment by ZLY201** [comment]
Everything looks fine.
