### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by Justman10000** [js-sdsl/js-sdsl#38]
Hi, this module is required of a project I'm working on! Only this always comes:

> Error: Cannot find module '<kuma_path>\node_modules\js-sdsl\dist\cjs\index.js

**Comment by Justman10000** [comment]
@ZLY201

**Comment by ZLY201** [comment]
> Hi, this module is required of a project I'm working on! Only this always comes:
> 
> > Error: Cannot find module '<kuma_path>\node_modules\js-sdsl\dist\cjs\index.js

Maybe you need to show the error code and the version of js-sdsl.

**Comment by Justman10000** [comment]
> > Hi, this module is required of a project I'm working on! Only this always comes:
> > > Error: Cannot find module '<kuma_path>\node_modules\js-sdsl\dist\cjs\index.js
> 
> How can I reproduce it? @Justman10000
> 
> Maybe you need to show the error code and the version of js-sdsl.

Well, the requested dist directory doesn't even exist!

**Comment by ZLY201** [comment]
Try to run `rm -rf node_modules && npm run install`?

**Comment by Justman10000** [comment]
> Try to run `rm -rf node_modules && npm i`?

What does that change about the fact that `dist` is missing?

**Comment by Justman10000** [comment]
> Try to run `rm -rf node_modules && npm i`?

Since I have only these files:
![grafik](https://user-images.githubusercontent.com/49990629/190487392-89faf875-64e9-4b78-80c9-3850ef4576bf.png)

**Comment by ZLY201** [comment]
> > Try to run `rm -rf node_modules && npm i`?
> 
> What does that change about the fact that `dist` is missing?

You can see the unpacking files in cdn, all the versions have  `dist`: https://www.jsdelivr.com/package/npm/js-sdsl.

`rm -rf node_modules && npm i` this command can help you to reinstall all the package to get new `js-sdsl` files.

**Comment by Justman10000** [comment]
> > > Try to run `rm -rf node_modules && npm i`?
> > 
> > 
> > What does that change about the fact that `dist` is missing?
> 
> You can see the unpacking files in cdn, all the versions have `dist`: https://www.jsdelivr.com/package/npm/js-sdsl.
> 
> `rm -rf node_modules && npm i` this command can help you to reinstall all the packages to get new `js-sdsl` files.

However, npm pulls from [npmjs.com](https://www.npmjs.com/package/js-sdsl), not jsdelivr.com!

**Comment by ZLY201** [comment]
jsdelivr.com is a mirror of npm.

See https://www.jsdelivr.com/network/infographic.

Or you can visit npm to get the source file: https://npm.runkit.com/js-sdsl/dist/cjs/index.js

We can promise all the versions lager than 2.2.0 is legal. Please run `npm ls js-sdsl` or `yarn why js-sdsl` to see the version.

Maybe tell me how to reproduce it?

**Comment by Justman10000** [comment]
> jsdelivr.com is a mirror of npm.
> 
> See https://www.jsdelivr.com/network/infographic.
> 
> Or you can visit npm to get the source file: https://npm.runkit.com/js-sdsl/dist/cjs/index.js

I installed it manually via .tgz

**Comment by Justman10000** [comment]
> We can promise all the versions larger than 2.0.0 is legal. Please run `npm ls js-sdsl` or `yarn why js-sdsl` to see the version.

![grafik](https://user-images.githubusercontent.com/49990629/190685733-aad8c4e5-7d4b-472c-b803-8cd55f06ac5f.png)

**Comment by Justman10000** [comment]
> Maybe tell me how to reproduce it?

`npm install js-sdsl`

**Comment by Justman10000** [comment]
> Maybe tell me how to reproduce it?

`npm install js-sdsl`

<br>
package.json

```json
{
    "dependencies": {
        "js-sdsl": "latest"
    },
    "devDependencies": {
        "js-sdsl": "latest"
    }
}
```

**Comment by ZLY201** [comment]
Sorry, I cannot reproduce it.

I tried the follow commands:

- npm install mqtt
- npm install number-allocator
- npm install js-sdsl@latest
- npm install js-sdsl
- npm install js-sdsl --save-dev
- get `.tgz` from https://registry.npmjs.org/js-sdsl/-/js-sdsl-4.1.4.tgz

All the results with folder `dist`.

I don't think it's caused by this package.

**Comment by ZLY201** [comment]
Please check your `npm` version and config.
