### ISSUE TITLE
[feature request] insert with hint for TreeContainers

### ISSUE THREAD

**Issue by redboltz** [js-sdsl/js-sdsl#8]
**Is your feature request related to a problem? Please describe.**

I want to update the element in the TreeContainer (e.g. OrderedSet), but it is prohibited.
It is reasonable because updated element could insert the different position.

However, users sometimes know the updated element is still the same position.
For example,
```
Before update:
    V
[1, 3, 5]

After update:
    V
[1, 4, 5]
```

When I want to update the element, I need to do the following steps:

1. `container.find(key)` the element's iterator. Then got `it`.
2. `container.eraseElementByIterator(it)`
3. Create the new element based on the gotten element and insert it.

Step1 and 3 are `O(logN)` time complexity.
I want to eliminate Step3 cost.

**Describe the solution you'd like**
js-sdsl's design refers to C++ STL.
C++ `std::set::insert` has `insert(hint, value)` overload.
https://en.cppreference.com/w/cpp/container/set/insert
See (3) (4) overloads.

> Since C++ 11
> 3-4) Amortized constant if **the insertion happens in the position just before the hint**, logarithmic in the size of the container otherwise.

`container.eraseElementByIterator(it)` at the step2 returns the iterator just after the erased element.
So if I use the returned iterator as the hint, then the hint iterator is **the insertion happens in the position just before the hint**.

So the steps become as follows:

1. `container.find(key)` the element's iterator. Then got `it`.
2. `it = container.eraseElementByIterator(it)`
3. Create the new element based on the gotten element and insert it **with hint**. `container.insertWithHint(it, 4)`

Step3 becomes O(1) time complexity thanks to the hint `it`.

I guess that js-sdsl can implement similar way to the C++ one.

**Describe alternatives you've considered**

Directly modify the element value by user's risk. However, insert() with hint achieves the same goal (eliminate extra O(logN) time complexity) more elegant way.

**Additional context**

libc++ implementation of `std::set::insert(hint, value)`
https://github.com/llvm-mirror/libcxx/blob/2f961a057f1ecb29d40892fe9198fe4e4b5c5619/include/set#L704-L711

**Comment by ZLY201** [comment]
I've gone and looked at C++'s overloaded function for insert. But unfortunately, although it can improve efficiency, it is still O(logn) because it needs to self-balance after insertion.

I think you need a function which can change element by iterator while the tree is still balanced.

```javascript
const st = new OrderedSet([1, 2, 3]);
// Change begin iterator's key to 0 but maintain balance.
// Then `st` will be [0, 2, 3].
st.updateByIterator(st.begin(), 0);
```

Is this what you want?

**Comment by ZLY201** [comment]
We will also consider adding the overloaded function of insert to the function.

**Comment by redboltz** [comment]
> I've gone and looked at C++'s overloaded function for insert. But unfortunately, although it can improve efficiency, it is still O(logn) because it needs to self-balance after insertion.

Ah, updating by remove and insert changes the number of elements. The change could trigger self-barance, I guess.
Hmm...

> I think you need a function which can change element by iterator while the tree is still balanced.
> 
> ```js
> const st = new OrderedSet([1, 2, 3]);
> // Change begin iterator's key to 0 but maintain balance.
> // Then `st` will be [0, 2, 3].
> st.updateByIterator(st.begin(), 0);
> ```
> 
> Is this what you want?
> 
> Because this is done internally, user does not need to worry about its security, the function will judge it.

It is nice.
It is similar concept to Boost.MultiIndex's modify function.

See https://www.boost.org/doc/libs/1_80_0/libs/multi_index/doc/reference/ord_indices.html#modifiers

```cpp
template<typename Modifier> bool modify(iterator position,Modifier mod);
```

I considered 2nd parameter.
If it is an updated value as follows, you can't access the original value.

```js
st.updateByIterator(st.begin(), 0);
```

But if it is a function, you can access and modify the original value as follows:

```js
st.updateByIterator(st.begin(), (value) => { --value; });
```

C++ can enforce the parameter as reference but I'm not sure JS can do that. If the value type is primitive type, then it has copy semantics so maybe object wripping would be required.

However, I think that the following approach is good enough. So modifer function version is not required. Value version is simple and good.

```js
const it = st.begin();
const updated = it.pointer - 1; // 1 - 1 => 0
st.updateByIterator(it, updated);
```

> We will also consider adding the overloaded function of insert to the function.

Ah, TypeScript can overload function if the number of parameters are different. It's nice.

**Comment by ZLY201** [comment]
The test version 4.1.4-beta.0 has been released, if there are no bug reports within a week, we will released the official version.
